services:
  marketflow:
    build: 
      context: .
    container_name: marketflow
    ports:
      - "8400:8400"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EXCHANGE1_HOST=exchange1  # ← используем имена сервисов
      - EXCHANGE2_HOST=exchange2
      - EXCHANGE3_HOST=exchange3
    depends_on:
      - db
      - redis
      - exchange1
      - exchange2
      - exchange3
    command: sh -c "sleep 5 && /marketflow"
    networks:
      - marketflow-network

  db:
    image: postgres:16
    container_name: my_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - marketflow-network

  redis:
    image: redis:7-alpine
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - marketflow-network

  exchange1:
    image: exchange1:latest
    ports:
      - "40101:40101"
    networks:
      - marketflow-network
    restart: unless-stopped

  exchange2:
    image: exchange2:latest
    ports:
      - "40102:40102"
    networks:
      - marketflow-network
    restart: unless-stopped

  exchange3:
    image: exchange3:latest
    ports:
      - "40103:40103"
    networks:
      - marketflow-network
    restart: unless-stopped

networks:
  marketflow-network:
    driver: bridge

volumes:
  db_data:
  redis_data: